server:
  port: 8082
  servlet:
    contextPath: /springboottraining
# note : server.port の値を省略すると暗黙で8080になる
# 80 (本番用)
# 8080 (開発用)
# 8081 (開発用2)何らかの理由でサーバに複数並べる時など

logging:
  level:
    org:
      springframework:
      security: DEBUG

spring:
  application:
    name: springboottraining
  config:
    import: 'classpath:META-INF/build-info.properties'
  datasource:
    url: jdbc:h2:~/testdb
    driver-class-name: org.h2.Driver
    username: h2db
    password: h2db
  sql:
    init:
      mode: always # note : 起動時にdata.sqlを実行する. 開発中の初期化に使う
  h2:
    console:
      enabled: true
  messages:
    basename: messages, validationMessages
    cache-duration: -1